#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.main_sources = []

env_main = env.Clone()

env_main.add_source_files(env.main_sources, "*.cpp")

if env["steamapi"] and env.editor_build:
    env_main.Append(CPPDEFINES=["STEAMAPI_ENABLED"])

lib = env_main.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
