#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.servers_sources = []

env.add_source_files(env.servers_sources, "register_server_types.cpp")

SConscript("physics_2d/SCsub")
SConscript("physics_3d/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
