#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.scene_sources = []

# Godot source files
env.add_source_files(env.scene_sources, "*.cpp")

# Chain load SCsubs
SConscript("main/SCsub")
SConscript("resources/SCsub")

# Build it all as a library
lib = env.add_library("scene", env.scene_sources)
env.Prepend(LIBS=[lib])
